### ISSUE TITLE
Add log rotation?

### ISSUE THREAD

**Issue by adigitoleo** [void-linux/socklog-void#1]
Hi,

I'm new to void, and before when I was using systemd logging I would run `logrotate` to keep log files under control. I see that socklog/svlogd has [built-in rotation support](http://smarden.org/socklog/benefits.html#logrotation), which is cool, and I wonder if it would be useful to add some rotation limits to these default profiles. Alternatively, I can edit the socklog .conf files, but will that be overwritten by socklog updates?

Cheers

**Comment by Duncaen** [comment]
Those specific configuration files are marked as such and will not be overwritten, see: `xbps-query -p conf_files socklog-void` or just `xbps-query -S socklog-void`.

**Comment by adigitoleo** [comment]
Nice, thanks.
