### ISSUE TITLE
svlogtail: `cat` error message when no `*.[us]` logs exist

### ISSUE THREAD

**Issue by camoz** [void-linux/socklog-void#2]
On a fresh void install I just got an error message when using `svlogtail` on a service that does not yet have rotated logs (`*.[us]`):

```
[root@rootfs /]# svlogtail xbps
cat: '/var/log/socklog/xbps/*.[us]': No such file or directory
```

After that the `current` log is displayed.

Maybe there is an elegant way in `sh` to check whether a glob expands? Then that could be used as a guard for https://github.com/void-linux/socklog-void/blob/master/svlogtail#L23?

**Comment by leahneukirchen** [comment]
Please try https://github.com/void-linux/socklog-void/pull/4

**Comment by camoz** [comment]
Tested, works for me.
