### ISSUE TITLE
svlogtail: Add `-f` option for following the log like in `tail -f`

### ISSUE THREAD

**Issue by camoz** [void-linux/socklog-void#3]
Logs often have many lines, and then it's often useful to use a pager to display them, because 1) one is brought directly to the beginning of the log and does not have to search for it, and 2) one can search the file interactively using a pager like `less`.

Maybe I'm missing something, but right now I have to first pipe the output to `less`, then when I go to the bottom of the content the pager "loses input": I have to `Ctrl-C` the tail command, then I can use the pager as usual.

I had the idea of implementing a `-f` flag just like in the regular `tail` command. Benefits:

1. More coherent with the behavior of `tail` (which many users are familiar with).
2. One could `svlogtail | less` like usual without the dangling `tail` at the end that needs be `Ctrl-C`'.

If there is interest I think I could implement this.

**Comment by leahneukirchen** [comment]
`svlogtail` uses `tail -F` internally already, I don't think you can do that much better else way?

**Comment by camoz** [comment]
`tail` by default doesn't `follow`.

What I want to do is basically wrap the `tail` commands in an `if` statement, checking for whether `-f` was supplied to `svlogtail`.

**Comment by leahneukirchen** [comment]
-F is -f with according for file replacement.

**Comment by camoz** [comment]
`tail`: doesn't follow
`tail -f`: follows

I want it so that:

`svlogtail`: doesn't follow
`svlogtail -f`: follows

But right now it's:

`svlogtail`: follows
`svlogtail -f`: error

**Comment by leahneukirchen** [comment]
Ok, I misunderstood the request, you want to add `-f` but disable it by default. That should be easy to do.

**Comment by camoz** [comment]
Thank you!
