### ISSUE TITLE
svlogtail: show only from current boot

### ISSUE THREAD

**Issue by dkwo** [void-linux/socklog-void#6]
Would it be possible to add an option to `svlogtail` to only show logs from current boot?
I was trying to replicate the behaviour of `journalctl -p 3 -b`, right now I can do `svlogtail errors`

**Comment by leahneukirchen** [comment]
It's not obvious to find the logs of the current boot to me.

**Comment by dkwo** [comment]
I'm closing this, as it's not an issue, just something it could be nice to have :)
